[package]
name = "rust-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.55", features = ["derive"] }
encoding_rs = "0.8.35"
hostname = "0.4.2"

[profile.release]
opt-level = "z"  # Optimize for size
lto = true       # Enable Link Time Optimization
codegen-units = 1 # Reduce parallelism for better optimization
panic = "abort"   # Remove panic unwinding
strip = true      # Strip symbols
